### PR TITLE
Add clean rule to Makefile

### PR DESCRIPTION
**Pull request by alarsyo**
**What this PR does / why we need it**:

Makefile was missing a simple clean rule

### CODE REVIEW

**Comment by stp-ip** [comment]
Dependency failure for tests. Restrying not. Once it's green, I'll merge.

**Comment by stp-ip** [comment]
So a recent change in Caddy let's the build fail due to it requiring go 1.9 at least. That should be updated within this PR to fix the tests. Ref: 
https://github.com/mholt/caddy/pull/2009#issuecomment-362771995

**Comment by alarsyo** [comment]
Oh, weird, I didn't get any email from Travis :/ I'll fix that !

**Comment by stp-ip** [comment]
We are hanging with the docker login it seems.

**Comment by alarsyo** [comment]
That's weird, the login command hasn't been touched when moving the Makefile to CI, so something changed with Travis or the docker CLI since then ? 

Login works as expected on my machine when passing username as an argument, however I get the login prompt if I pass `docker login --username=""` with nothing for the username. Could this be that Travis doesn't export the environment variables correctly ?

**Comment by alarsyo** [comment]
I didn't catch that in the build log: https://travis-ci.org/txtdirect/txtdirect/jobs/339498385#L444

Reading through the link now

**Comment by alarsyo** [comment]
Oh. Looks like I can't create a pull request from my fork if we want the CI to deploy. Makes sense.

**Comment by stp-ip** [comment]
Can we make that deploy only run on master? So that the deploy doesn't fail the whole check?

**Comment by alarsyo** [comment]
Hopefully this does the trick!

**Comment by alarsyo** [comment]
Travis seems to test PRs as if the branch was merged with master, so that still triggers the deploy. I'll try something else.

**Comment by alarsyo** [comment]
Oops, my use of the keywords was wrong... 

This one seems to have worked, Travis doen't list the deploy stage anymore. Yay!

I guess a rebase if probably needed, should I just keep one commit for all the Travis stuff ?

**Comment by stp-ip** [comment]
Rebase cleaning up history might be good.

Not sure about deploy. On master seems good enough considering that for dev or testing one can built locally using the make file, but if it's easily done we can also re-enable on branches and block PRs.

**Comment by alarsyo** [comment]
Sorry for long delay, should be good now!

**Comment by stp-ip** [comment]
Awesome. \o/

**Pull request merged**
