### PR TITLE
Add Docker deployment to CI

### PR DESCRIPTION
**Pull request by alarsyo**
Still room for (a lot of) improvement

### CODE REVIEW

**Comment by stp-ip** [comment]
Code looks good so far. Will test the image hopefully later today.
Another thing still missing is the build on tags, but not a high priority for now.

**Comment by alarsyo** [comment]
Build on tags ?

**Comment by stp-ip** [comment]
Currently you are only building each commit on master as development build. Later we might want to also build releases such as v0.0.1. These would be tagged as git tag and the build would then run on the tagged release and push to txtdirect:v0.0.1-$ref.

**Comment by alarsyo** [comment]
Got it.

**Comment by alarsyo** [comment]
This should do the trick!

**Comment by stp-ip** [comment]
Great. After a rebase and me testing another round it should be ready to merge.

**Comment by stp-ip** [comment]
My tests seem to work. Waiting for the rebase and then merge \o/

**Comment by alarsyo** [comment]
Rebased

**Pull request merged**
