### PR TITLE
Refactor placeholders and support placeholders in dns records

### LINKED ISSUE #91: [placeholder] Placeholder specific redirects
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently placeholders can be used to add information to the redirected url.

**What you expected to happen**:
Use placeholder information to handle the redirect especially.
Such as `from={method}` could lookup:
```
_redirect.get.example.com
_redirect.post.example.com
```

**Anything else we need to know?**:
Needs discussion. Just a thought and most likely not that useful, just wanted to get the idea out.

### PR DESCRIPTION
**Pull request by erbesharat**
**What this PR does / why we need it**:
Puts placeholder code in a separate file and uses ``parsePlaceholders`` in record parse method to support placeholders inside TXT records too.

**Which issue this PR fixes** *(optional - uncomment and add issue)*:
fixes #91 

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by erbesharat** [comment]
@stp-ip I just think it would be a good idea to let the user use placeholders in records too. Have no idea if it's necessary or not but they can do something like getting a regex from ``{query}`` placeholder and use it in ``rec.re``.

**Comment by stp-ip** [comment]
Still trying to wrap my head around the use case. Can you give a specific example on how {query} + regex would be used.

**Comment by erbesharat** [comment]
URI: https://example.com/path/123/somewhere?regex=(\\d+)
Record: ``"v=txtv0;re={?regex};type=path;code=302"``

This way user can pass the custom regex using query strings too. I don't know if it's going to be even used by anyone or not. Just a use case that came to my mind :smile:

**Comment by stp-ip** [comment]
Something of a interesting use case.
The domain opensourcesoftware.rocks could be used to automatically redirect a subdomain using the "i'm lucky" search from google. Not yet sure how and how that relates to this issue so.

kubernetes.opensourcesoftware.rocks -> https://www.google.com/search?btnI=1&q=kubernetes -> kubernetes.io

```
v=txtv0;to=https://www.google.com/search?btnI=1&q={;type=host;code=302
```

**Pull request merged**
